name: flutter_soloud
description: >-
  A low-level audio plugin for Flutter,
  mainly meant for games and immersive apps.
  Based on the SoLoud (C++) audio engine.
version: 3.1.4
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
topics:
  - audio
  - player
  - games

screenshots:
  - description: "audio FFT data"
    path: img/screenshot.png

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  http: ^1.3.0
  logging: ^1.3.0
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8
  web: ^1.1.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
        default_package: true

  assets:
    # These assets are only needed for the web platform.
    # Waiting for https://github.com/flutter/flutter/issues/65065 and
    # https://github.com/flutter/flutter/issues/8230 to be addressed.
    # to make a conditional build.
    - web/worker.dart.js
    - web/libflutter_soloud_plugin.js
    - web/libflutter_soloud_plugin.wasm
    - web/init_module.dart.js
